name: default

on:
  push:
    branches:
    - '*'

jobs:
  build:
    # This job will run on ubuntu virtual machine
    runs-on: ubuntu-latest
    steps:
    
    # Setup Java environment in order to build the Android app.
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    
    # Setup the flutter environment.
    - uses: subosito/flutter-action@v1
      with:
        channel: 'beta' # 'dev', 'alpha', default to: 'stable'
        # flutter-version: '1.12.x' # you can also specify exact version of flutter
    
    # Get flutter dependencies.
    - run: flutter pub get
    
    # Check for any formatting issues in the code.
    - run: flutter format --set-exit-if-changed .
    
    # Statically analyze the Dart code for any errors.
    - run: flutter analyze .
    
    # Run widget tests for our flutter project.
    - run: flutter test
    - run: sudo apt install clang cmake ninja-build pkg-config libgtk-3-dev wget curl cmake
    - run: flutter upgrade --force
    - run: flutter config --no-analytics
    - run: flutter pub get
    - run: flutter doctor
    - run: flutter test
    - run: flutter config --enable-linux-desktop --verbose
    - run: flutter build linux --release --verbose
    - uses: actions/upload-artifact@v2
      with:
        name: build-linux
        path: build/linux
