name: default

on:
  push:
    branches:
    - '*'

jobs:

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.0.4'
      - run: sudo apt install clang cmake ninja-build pkg-config libgtk-3-dev wget curl
      - run: flutter config --no-analytics
      - run: flutter pub get
      - run: flutter doctor
      - run: flutter test
      - run: flutter config --enable-linux-desktop --verbose
      - run: flutter build linux --release --verbose
      - uses: actions/upload-artifact@v2
        with:
          name: build-linux
          path: build/linux
